CREATE TABLE Customer(taxID integer, name char(20), username char(15), password char(15), address char(30), state char(2), phone char(12), email char(20), ssn char(11), PRIMARY KEY(taxID));
CREATE table marketAccount(taxID integer, maID integer, balance float, primary key(taxID), foreign key(taxID) references Customer(taxID));
ALTER TABLE `bpatientDB`.`marketAccount` CHANGE COLUMN `maID` `maID` INT(11) NULL AUTO_INCREMENT , ADD UNIQUE INDEX `maID_UNIQUE` (`maID` ASC);
CREATE TABLE Stock(stockID char(3), closingprice float, currentprice float, primary key(stockID));
CREATE TABLE Actor(stockID char(3), name char(20), birthday char(20), primary key(stockID), foreign key(stockID) references Stock(stockID));
CREATE TABLE stockAccount(saID integer, taxID integer, numshares integer, stockID char(3), boughtAt float, PRIMARY KEY(saID), foreign key(taxID) references Customer(taxID), foreign key(stockID) references Stock(stockID));
ALTER TABLE `bpatientDB`.`stockAccount` CHANGE COLUMN `saID` `saID` INT(11) NOT NULL AUTO_INCREMENT , ADD UNIQUE INDEX `saID_UNIQUE` (`saID` ASC);
CREATE TABLE Transactions(tid integer, type char(10), amount float, date char(10), taxID integer, stockID char(3), numshares integer, primary key(tid), foreign key(taxID) references Customer(taxID), foreign key(stockID) references Stock(stockID));
ALTER TABLE `bpatientDB`.`Transactions` CHANGE COLUMN `tid` `tid` INT(11) NOT NULL AUTO_INCREMENT , ADD UNIQUE INDEX `tid_UNIQUE` (`tid` ASC);
CREATE TABLE Contract(cid integer, title char(20), totalvalue float, year integer, role char(10), stockID char(3), primary key(cid), foreign key(stockID) references Actor(stockID));
ALTER TABLE `bpatientDB`.`Contract` CHANGE COLUMN `cid` `cid` INT(11) NOT NULL AUTO_INCREMENT , ADD UNIQUE INDEX `cid_UNIQUE` (`cid` ASC);
CREATE TABLE Manager(taxID integer,name char(20), username char(15), password char(15), address char(30), state char(2), phone char(10), email char(20), ssn char(11), PRIMARY KEY(taxID));